package com.nagaja.the330.utils

object ScreenId {
    const val SCREEN_LANGUAGE_FIRST = "SCREEN_LANGUAGE_FIRST"
    const val SCREEN_PERMISSION = "SCREEN_PERMISSION"
    const val SCREEN_LOGIN = "SCREEN_LOGIN"
    const val SCREEN_SIGNUP_MAIL = "SCREEN_SIGNUP_MAIL"
    const val SCREEN_FIND_RESET_TEMPLACE = "SCREEN_FIND_RESET_TEMPLACE"
    const val SCREEN_VERIFY_OTP = "SCREEN_VERIFY_OTP"
    const val SCREEN_MAIN = "SCREEN_MAIN"
    const val SCREEN_EDIT_PROFILE = "SCREEN_EDIT_PROFILE"
    const val SCREEN_FAV_COMPANY = "SCREEN_FAV_COMPANY"
    const val SCREEN_APPLY_COMPANY = "SCREEN_APPLY_COMPANY"
    const val SCREEN_APPLY_COMPANY_PRODUCT_INFO = "SCREEN_APPLY_COMPANY_PRODUCT_INFO"
}